GET http://localhost:3001

###
POST http://localhost:3001/api/register
Content-Type: application/json

{
    "username":"Madhubabu",
    "name":"madhu",
    "email":"madhu2025@gmail.com",
    "password":"madhu@2025"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"Veerababu",
    "password":"veeru@2025"
}

###
PUT http://localhost:3001/api/user/677defcf264f576076407997
Content-Type: application/json

{
    "name":"veeresh",
    "email":"veeru2024@gmail.com"
}

###
DELETE http://localhost:3001/api/users/677defcf264f576076407997


###
GET http://localhost:3001/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2UwZmU3ZTg0Nzg3NmEyODA4ZDZiMiIsImlhdCI6MTczNjMxNzIxOSwiZXhwIjoxNzQ0MDkzMjE5fQ.EZ2QcXwTqaQlWGlPElrLyVK3VMDbJrzIKwURwlTs7KQ

###
GET http://localhost:3001/api/users
